name: prt
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  path: ^1.8.3
  flutter_dash: ^1.0.0
  image_picker: ^1.0.2
  provider: ^6.0.5
  agora_rtc_engine: ^6.2.2
  permission_handler: ^10.4.3
  pin_code_fields: ^8.0.1 
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  dio: ^5.3.2
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/splashImages.png
    - images/mother.jpeg
    - images/GoogleLogo.png
    - images/FacebookLogo.png
    - images/Pembantu.png
    - images/Pencari.png
    - images/check.png
    - images/emptyCheck.png
    - images/filCheck.png
    - images/option.png
    - images/NavigateBack.png
    - images/exclamation.png
    - images/Love.png
    - images/Bell.png
    - images/search.png
    - images/filter.png
    - images/SaldoBg.png
    - images/NavigateNext.png
    - images/Add.png
    - images/Dolar.png
    - images/PeopleIcon.png
    - images/TimeIcon.png
    - images/WhiteLove.png
    - images/Phone.png
    - images/Home.png
    - images/Dolar.png
    - images/Message.png
    - images/User.png
    - images/Ava.jpg
    - images/David.jpg
    - images/Emily.jpg
    - images/John.jpg
    - images/Michael.jpg
    - images/Olivia.jpg
    - images/Robert.jpg
    - images/Sarah.jpg
    - images/Sophia.jpg
    - images/William.jpg
    - images/NavBackTransparant.png
    - images/dolarStack.png
    - images/announce.png
    - images/HomePlain.png
    - images/Star.png
    - images/TopUpBG.png
    - images/x.png
    - images/PayMethodBG.png
    - images/PayMethodDownBG.png
    - images/wallet.png
    - images/NavNext.png
    - images/BRILogo.png
    - images/BCALogo.png
    - images/MandiriLogo.png
    - images/BNILogo.png
    - images/MessageGreen.png
    - images/AppBarChatBG.png
    - images/NavBackGreen.png
    - images/InterviewGreen.png
    - images/sent.png
    - images/rantai.png
    - images/dolarGreen.png
    - images/profileBG.png
    - images/NavNextNoBG.png
    - images/location.png
    - images/key.png
    - images/questionMark.png
    - images/exclamationMark.png
    - images/documentSign.png
    - images/logoutSign.png
    - images/xNoBG.png
    - images/pembatuWhite.png
    - images/pencariWhite.png
    - images/end_call.png
    - images/mic_off.png
    - images/reverse_cam.png
    - images/cam_off.png
    - images/cam.png
    - images/mic.png
    - images/interviewTransparant.png
    - images/jadwalSet.png
    - images/incomingCallBG.png
    - images/incomingCallPhotoDumb.png
    - images/pickUpCall.png
    - images/rejectCall.png
    - images/navUpDouble.png
    - images/navUp.png
    - images/borderIncomingCall.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
    - family: Asap
      fonts:
        - asset: fonts/Asap-Regular.ttf
        - asset: fonts/Asap-SemiBold.ttf
        - asset: fonts/Asap-Medium.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
