// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjvlI4sphUsLDzHFkhzYUOyUXV1KmvnYA',
    appId: '1:186858847390:web:d2cf790abd15de22a74f8f',
    messagingSenderId: '186858847390',
    projectId: 'pembantu-application',
    authDomain: 'pembantu-application.firebaseapp.com',
    storageBucket: 'pembantu-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU5C9283-ZQFimol1RqjDpsBTGK8Kz3K4',
    appId: '1:186858847390:android:7b163461d84e1537a74f8f',
    messagingSenderId: '186858847390',
    projectId: 'pembantu-application',
    storageBucket: 'pembantu-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDk2w6l75zhqUzmepvfbpgI8SGWrhoCoc',
    appId: '1:186858847390:ios:d06cac0cc7bf21b7a74f8f',
    messagingSenderId: '186858847390',
    projectId: 'pembantu-application',
    storageBucket: 'pembantu-application.appspot.com',
    iosBundleId: 'com.example.prt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDk2w6l75zhqUzmepvfbpgI8SGWrhoCoc',
    appId: '1:186858847390:ios:d7253cfc43f0a513a74f8f',
    messagingSenderId: '186858847390',
    projectId: 'pembantu-application',
    storageBucket: 'pembantu-application.appspot.com',
    iosBundleId: 'com.example.prt.RunnerTests',
  );
}
